### Admin signup
POST http://localhost:5000/signup/admin HTTP/1.1
Content-Type: application/json

{
    "email" : "dvishu2610@gmail.com",
    "username" : "Divyanshu",
    "password" : "dvishu$123"
}

### Admin login
POST http://localhost:5000/login/admin HTTP/1.1
Content-Type: application/json

{
    "username" : "Divyanshu",
    "password" : "dvishu$123"
}

### Add book (admin)
POST http://localhost:5000/admin/add_book HTTP/1.1
Content-Type: application/json

{
    "title": "Micro Electronics",
    "author": "Sedra and Smith",
    "ISBN": "abc1101011010",
    "details": "The best solution for amplifiers"
}

### Remove book
DELETE http://localhost:5000/admin/remove_book/66601afdc0cd4ce0c6358941 HTTP/1.1

### Get all books
GET http://localhost:5000/admin/all_books HTTP/1.1

### Get all issued books
GET http://localhost:5000/admin/issued_books HTTP/1.1

### Get all users
GET http://localhost:5000/admin/user_list HTTP/1.1

### Issue Requests
GET http://localhost:5000/admin/requests HTTP/1.1

### Resolve issue
PUT http://localhost:5000/admin/issue/6661585ad3a85e52d71ef407 HTTP/1.1

### Accept return
DELETE http://localhost:5000/admin/return/6660259dec675a0311b313c9 HTTP/1.1

### Logout admin
DELETE http://localhost:5000/admin/logout HTTP/1.1