### Get - OTP
POST http://localhost:5000/get-otp?type=user HTTP/1.1
Content-Type: application/json

{
    "email" : "ui22ec23@iiitsurat.ac.in"
}

### User signup
POST http://localhost:5000/signup/user?type=user HTTP/1.1
Content-Type: application/json

{
    "email" : "ui22ec23@iiitsurat.ac.in",
    "contact": "9580126717",
    "username" : "ui22ec23",
    "password" : "svishwa@123",
    "otp": "244502"
}

### User login
POST http://localhost:5000/login/user HTTP/1.1
Content-Type: application/json

{
    "username" : "ui22ec23",
    "password" : "svishwa@123"
}

### Get list of all books
GET http://localhost:5000/user/all_books HTTP/1.1

### Request book
POST http://localhost:5000/user/ask/6661527100d54b313ebe7c56 HTTP/1.1

### Get list of issued books
GET http://localhost:5000/user/issued HTTP/1.1

### Get profile
GET http://localhost:5000/user/profile HTTP/1.1

### Update profile
PUT http://localhost:5000/user/profile HTTP/1.1
Content-Type: application/json

{
    "name": "Divyanshu Vishwakarma",
    "idCard": "This is the image string of id"
}

### Logout user
DELETE http://localhost:5000/user/logout HTTP/1.1