### Get - OTP
POST http://localhost:5000/get-otp?type=user HTTP/1.1
Content-Type: application/json

{
    "email" : "[email]"
}

### User signup
POST http://localhost:5000/signup/user?type=user HTTP/1.1
Content-Type: application/json

{
    "email" : "[email]",
    "contact": "[mobile no.]",
    "username" : "[username]",
    "password" : "[password]",
    "otp": "[otp]"
}

### User login
POST http://localhost:5000/login/user HTTP/1.1
Content-Type: application/json

{
    "username" : "[username]",
    "password" : "[password]"
}

### Get list of all books
GET http://localhost:5000/user/all_books HTTP/1.1

### Request book
POST http://localhost:5000/user/ask/6661527100d54b313ebe7c56 HTTP/1.1

### Get list of issued books
GET http://localhost:5000/user/issued HTTP/1.1

### Get profile
GET http://localhost:5000/user/profile HTTP/1.1

### Update profile
PUT http://localhost:5000/user/profile HTTP/1.1
Content-Type: application/json

{
    "name": "[your name]",
    "idCard": "[id card string]"
}

### Get notifications
GET http://localhost:5000/user/notification HTTP/1.1

### Read notifications
DELETE http://localhost:5000/user/notification/66d97ad26902dd63e58b96dc HTTP/1.1

### Logout user
DELETE http://localhost:5000/user/logout HTTP/1.1